[build-system]
requires = [
  "setuptools>=40",
]
build-backend = "setuptools.build_meta"

[tool.towncrier]
package = "yayarl"
filename = "CHANGES.rst"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/robinvandernoord/yayarl/issues/{issue}>`_"


[tool.cibuildwheel]
test-requires = "-r requirements/ci.txt"
test-command = "pytest {project}/tests"
# don't build PyPy wheels, install from source instead
skip = "pp*"
